name: mosersinministry
favicon: null
layout_spectrum: 0.34675259492360055
typography_spectrum: 0.11553149903193116
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.07207729434594512
  lightness: 0.9172773051541299
  saturation: 0.2371602300554514
  rhythmicContrast: 0.7360814597923309
purpose: []
